# Generated by Django 5.2.4 on 2025-09-24 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_is_active_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid and up to 30 characters.', regex='^\\+?[\\d\\s\\-x()]{7,30}$')]),
        ),
    ]
