# Generated by Django 5.2.4 on 2025-09-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_options_item_updated_at_alter_item_price_and_more'),
        ('suppliers', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='suppliers.supplier'),
        ),
    ]
