# Generated by Django 5.2.4 on 2025-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[('VIP', 'VIP'), ('REGULAR', 'Regular'), ('BLOCKED', 'Blocked')], default='REGULAR', max_length=20),
        ),
    ]
